const officialWebsites = [
  'https://www.allrecipes.com/recipe/143069/super-delicious-zuppa-toscana/',
  'https://www.foodnetwork.com/recipes/tyler-florence/cranberry-orange-sauce-recipe3-1946636',
  'https://www.simplyrecipes.com/recipes/loaded_sheet_pan_nachos/',
  'https://www.delish.com/cooking/recipe-ideas/a41300962/roasted-cauliflower-salad-recipe/',
  'https://www.epicurious.com/recipes/food/views/brooklyn-blackout-cake',
  'https://tasty.co/recipe/mozzarella-stick-onion-rings',
  'https://www.tasteofhome.com/recipes/apple-honey-dutch-baby/',
  'https://www.seriouseats.com/savory-asparagus-mushroom-leek-and-cheese-galette',
  'https://www.myrecipes.com/recipe/easy-chili',
  'https://therecipecritic.com/strawberry-banana-bread/',
  'https://food52.com/recipes/3658-maple-yogurt-pound-cake',
  'https://www.washingtonpost.com/recipes/bitter-tropics/18440/',
  'https://www.budgetbytes.com/sushi-bowls-sriracha-mayo/',
  'https://www.today.com/recipes/roasted-pumpkin-ramen-recipe-t268656',
  'https://www.recipegirl.com/apple-walnut-salad-with-cranberry-vinaigrette/',
  'https://www.cookingclassy.com/white-chicken-chili/',
  'https://www.recipetineats.com/cinnamon-apple-bread/',
  // 'https://www.realcaliforniamilk.com/recipe/bean-and-cheese-molletes',
  'https://www.bonappetit.com/recipe/dry-rubbed-roast-turkey',
  'https://www.marmiton.org/recettes/recette_bechamel_23880.aspx',
  'https://www.ricardocuisine.com/recettes/9536-poulet-grille-salade-de-tomates-et-poivrons-grilles-aux-olives',
  'https://www.cuisineaz.com/recettes/gratin-de-courgettes-a-la-ricotta-54699.aspx',
  // 'https://www.poulet.ca/recettes/ramequins-doeufs-et-de-poitrines-de-poulet-roti/',
  // 'https://www.recettes.qc.ca/recettes/recette/fish-and-chips-comme-en-angleterre-169043',
  // 'https://www.recettesdici.com/fr/categorie-de-plat/11/soupes-et-potages/1068/potage-de-carottes-a-lorange',
]

export default officialWebsites
