'use client'
import Head from 'next/head'
import React, { useEffect } from 'react'
import ReactTooltip from 'react-tooltip'
import { useTranslation } from 'react-i18next'

import useIsStandalonePWA from '@/hooks/useIsStandalonePWA'
import useEventListener from '@/hooks/useEventListener'
import useIsMobile from '@/hooks/useIsMobile'

type Props = {
  className?: string
  children: React.ReactNode
  title?: string
  onScroll?: (number: number) => void
  scroll?: number
  style?: React.CSSProperties
}

const Page = ({
  className = '',
  children,
  title,
  onScroll = () => {},
  scroll = 0,
  style,
}: Props) => {
  useEffect(() => {
    window.scrollTo(0, scroll)
  }, [scroll])

  useEventListener('scroll', () => {
    onScroll(window.scrollY || 0)
  })

  const { t, i18n } = useTranslation('common')

  const isStandalonePWA = useIsStandalonePWA()

  const fullTitle = isStandalonePWA
    ? title
    : `${title ? `${title} - ` : ''}${t('_AppName')}`

  const isMobile = useIsMobile()

  const dir = i18n.dir()
  const locale = i18n.language

  useEffect(() => {
    document.body.dir = dir
  }, [dir])

  useEffect(() => {
    document.documentElement.setAttribute('lang', locale ?? '')
  }, [locale])

  return (
    <>
      <Head>
        <meta charSet="utf-8" />
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <title>{fullTitle}</title>
      </Head>
      {/* <ReactTooltip
        effect="solid"
        getContent={dataTip => dataTip}
        disable={isMobile}
        backgroundColor="black"
        delayShow={250}
      /> */}
      <div
        className={`relative bg-white overflow-auto scroll-auto select-none z-20	${className}`}
        style={style}
        id="page"
      >
        {children}
      </div>
    </>
  )
}

export default Page
